### ISSUE TITLE
API Rules Best Practices?

### ISSUE THREAD

**Issue by embowles93** [Rebackk-Team/pocketbase-adapter#3]
Hi there!

First of all, this is an awesome adapter - I love Pocketbase and have recently been learning how to use Next Auth so its exactly what I was looking for.

My question is around securing the collections in PB. In the readme it mentions to adjust the API rules to one's use case, but I could use some help with recommendations on how to lock things down. Right now I have all the collections from the Schema.json file wide open, which I imagine isn't a great idea in production. However, I'm not sure how to 'authenticate' the authentication process itself. 

Does it have something to do with the NEXTAUTH_SECRET that I have set up? Perhaps some way to create a rule that checks for that on incoming requests when a user signs up?

Thanks in advance!

**Comment by 0xsarwagya** [comment]
Hi @embowles93 Thankyou for your kind words.

So We are Using Admin Only Setup Right Now and Plan To Add Better API Rules Handling In The Future.

You Can Use This To Authenticate Your Users In An Admin Only Setup.

# Setup Pocketbase In Your Next.js App

```js
import { PocketBase } from "pocketbase";

export const getPocketbase = () => {
  // Get Pocketbase environment variables
  const { PB_URL, PB_ADMIN_EMAIL, PB_ADMIN_PASS } = process.env;

  // Check if environment variables are set
  if (!PB_URL || !PB_ADMIN_EMAIL || !PB_ADMIN_PASS) {
    // Throw an error if any of the environment variables are missing
    throw new Error("Missing Pocketbase environment variables");
  }

  // Create a new Pocketbase client
  const client = new PocketBase(PB_URL);

  // Authenticate the client with the admin credentials
  client.admins.authWithPassword(PB_ADMIN_EMAIL, PB_ADMIN_PASS);

  // Return the client
  return client;
};
```

In Your Next Auth AuthOptions Setup Pocketbase Adapter

Add the following code to your NextAuth configuration.

```js
import { AuthOptions } from "next-auth";
import { getPocketbase } from "@/lib/pb";
import { PocketBaseAdapter } from "@rebackk/pocketbase-adapter";

const authOptions : AuthOptions = {
  // Your NextAuth options
  // ...
  // Adding @ts-ignore to ignore TypeScript errors because we are using a custom adapter
  // @ts-ignore
  adapter: PocketBaseAdapter(getPocketbase()),
};
```

**Comment by 0xsarwagya** [comment]
PS : We are working on a new documentation site, which will be up in 1 or 2 weeks max :)

**Comment by Elliott-Bowles** [comment]
Thanks so much! This makes a lot of sense!! I will give it a try for now.

Perhaps another approach would be to inject the NEXTAUTH_SECRET token in the requests sent by the adapter, and to check those on the Pocketbase side with API rules. I'm no expert, but something like this could work?


```
createUser: async ({ id, ...data }) => {
      const createdUser = await p.collection("users").create({
        user_email: data.email,
        user_email_verified: data.emailVerified?.toString(),
        user_image: data.image,
        user_name: data.name,
      },{headers:{'X-NextAuth-Header' : 'process.env.NEXTAUTH_SECRET'});
```
Then on the API rules side of things, could create a rule like:

`@request.headers.X-NextAuth-Header= "XXXX"`

**Comment by 0xsarwagya** [comment]
That Seems Like A Great Idea. Converting This To A Feature Request. **Feel Free To Create A PR** If you wish to work on the feature :)

**Comment by 0xsarwagya** [comment]
@king04aman Feature Request :)

**Comment by Elliott-Bowles** [comment]
> That Seems Like A Great Idea. Converting This To A Feature Request. **Feel Free To Create A PR** If you wish to work on the feature :)

Sure thing! May have a go! Fair warning, I have no experience with things like unit tests :D so wish me luck...

**Comment by 0xsarwagya** [comment]
xD. Good Luck

**Comment by 0xsarwagya** [comment]
Completed In #4
